name: MacDaddy
batch:
  jdbc:
    driver: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb
    user: sa
    password:
    schema:
      script: classpath:/org/springframework/batch/core/schema-hsqldb.sql
spring:
  #profiles: dev
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ims
    username: root
    password: Z00xMu$1c
  # max-wait: 10000
  #  max-active: 50
   # test-on-borrow: true
  #  testOnBorrow: true
  #  validationQuery: select 1 from DUAL
  #  validationInterval: 30000
  #  maxActive: 100
  ##  maxIdle: 100
 #   minIdle: 10
 #   initialSize: 0
 #   maxWait: 30000
 #   testOnReturn: false
 #   testWhileIdle: false
 #   timeBetweenEvictionRunsMillis: 5000
 #   minEvictableIdleTimeMillis: 60000
 #   removeAbandoned: true
 #   removeAbandonedTimeout: 60
 #   logAbandoned: true

mail:
  from: brian@zooxmusic.com
  username: brian@zooxmusic.com
  password: Z00xMu$1c
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  smtp:
    auth: true
    starttls:
      enable: true


